#spring:
#  application:
#    name: intentparser
#  cloud:
#    config:
#      uri: http://localhost:8888
spring:
  data:
    neo4j:
      uri: http://172.23.239.174:7474
      username: neo4j
      password: root123
  application:
    name: intentparser
